### ISSUE TITLE
Updating to version 1.11.0 destroys German umlauts

### ISSUE THREAD

**Issue by plorenz-etes** [heimrichhannot/contao-hyphenator-bundle#6]
**Context**
Contao version: 4.9.24
Bundle version: 1.11.0
PHP version: 7.4

**Description**
After upgrading to version 1.11.0 (coming from 1.10.3), German umlauts are destroyed.

Before: `Der führende Anbieter...`
After: `Der fÃ¼hrende Anbieter...`

However, this is not an issue with broken character encoding. Viewing the source code, the following can be found:

`Der f&Atilde;&frac14;hrende Anbieter`

Downgrading to version 1.10.3 again solved the issue for me.

**Comment by koertho** [comment]
Hi, the only change in 1.11 was the library update. Could you try 1.11 with wa72/htmlpagedom 1.4 and check, if it still works?

**Comment by plorenz-etes** [comment]
I tried installing wa72/htmlpagedom 1.4.2 alongside heimrichhannot/contao-hyphenator-bundle 1.11.0 but it results in dependency errors which I unfortunately don't know how to resolve: https://pastebin.com/QZ2nZENQ

**Comment by koertho** [comment]
I just could reproduce this problem and hopefully fixed it in 1.11.1

**Comment by plorenz-etes** [comment]
Thank you, that fixed it for me as well! :)

**Comment by koertho** [comment]
Thanks for the feedback!

**Comment by plorenz-etes** [comment]
Seems like I was a bit too quick here - umlauts work fine now, but e.g. the following signs are replaced by question marks:

- – (`&ndash;`)
- ◀ (`&#9664;`) and ▶ (`&#9654;`), used for slider controls

I did a rollback to 1.10.3 for now.

**Comment by koertho** [comment]
Did you try 1.11.2?

**Comment by plorenz-etes** [comment]
Ah no, actually I didn't. Tried it now and it works fine, thank you!
