### ISSUE TITLE
Please remove dependency "php": "^7.1" in order to enable PHP 8 support

### ISSUE THREAD

**Issue by plorenz-etes** [heimrichhannot/contao-hyphenator-bundle#7]
**Context**
Contao version: 4.9.33
Bundle version: 1.11.2
PHP version: 8.0.22

**Description**
Although this bundle works perfectly with PHP 8, the composer.json doesn't allow installations with versions newer than 7.4. This should be changed.

I workarounded this by installing the bundle using the `--ignore-platform-reqs` command line option for composer and everything works fine after installation. However, it would be much cleaner if PHP 8 could be added as an option to the requirement list :-)

**Comment by koertho** [comment]
Fixed in 1.11.3
